version: "3"

services:
  airflow:

    image: apache/airflow
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./src/Services/AirflowDAGs:/usr/local/airflow/dags
    ports:
      - 8080:8080
    command: webserver


